export const personas = [{
    "id": 1, "nombre": "Kahlil", "edad": 53, "gender": "M", "sueldo": 1264, "pais": "Jamaica"
},
{ "id": 2, "nombre": "Betsy", "edad": 27, "gender": "F", "sueldo": 1582, "pais": "Japan" },
{ "id": 3, "nombre": "Haroun", "edad": 48, "gender": "M", "sueldo": 1951, "pais": "Lithuania" },
{ "id": 4, "nombre": "Beau", "edad": 51, "gender": "M", "sueldo": 1820, "pais": "Russia" },
{ "id": 5, "nombre": "Justinian", "edad": 43, "gender": "M", "sueldo": 1703, "pais": "Indonesia" },
{ "id": 6, "nombre": "Shellie", "edad": 21, "gender": "F", "sueldo": 1783, "pais": "France" },
{ "id": 7, "nombre": "Kori", "edad": 32, "gender": "F", "sueldo": 1461, "pais": "China" },
{ "id": 8, "nombre": "Gene", "edad": 41, "gender": "M", "sueldo": 1012, "pais": "Mexico" },
{ "id": 9, "nombre": "Helene", "edad": 50, "gender": "F", "sueldo": 1777, "pais": "Germany" },
{ "id": 10, "nombre": "Teirtza", "edad": 48, "gender": "F", "sueldo": 1807, "pais": "Belarus" },
{ "id": 11, "nombre": "Edik", "edad": 54, "gender": "M", "sueldo": 1059, "pais": "Venezuela" },
{ "id": 12, "nombre": "Cheri", "edad": 31, "gender": "F", "sueldo": 1412, "pais": "Indonesia" },
{ "id": 13, "nombre": "Erwin", "edad": 46, "gender": "M", "sueldo": 1691, "pais": "Indonesia" },
{ "id": 14, "nombre": "Giulio", "edad": 41, "gender": "M", "sueldo": 1231, "pais": "United States" },
{ "id": 15, "nombre": "Ingeberg", "edad": 24, "gender": "F", "sueldo": 1697, "pais": "China" },
{ "id": 16, "nombre": "Galvan", "edad": 32, "gender": "M", "sueldo": 1331, "pais": "Uzbekistan" },
{ "id": 17, "nombre": "Devin", "edad": 63, "gender": "M", "sueldo": 1321, "pais": "Kosovo" },
{ "id": 18, "nombre": "Hildegarde", "edad": 59, "gender": "F", "sueldo": 1706, "pais": "Uganda" },
{ "id": 19, "nombre": "Adelaide", "edad": 28, "gender": "F", "sueldo": 1346, "pais": "Indonesia" },
{ "id": 20, "nombre": "Free", "edad": 43, "gender": "M", "sueldo": 1556, "pais": "Philippines" },
{ "id": 21, "nombre": "Darren", "edad": 25, "gender": "M", "sueldo": 1072, "pais": "Portugal" },
{ "id": 22, "nombre": "Harrison", "edad": 61, "gender": "M", "sueldo": 1760, "pais": "Brazil" },
{ "id": 23, "nombre": "Trude", "edad": 47, "gender": "F", "sueldo": 1497, "pais": "China" },
{ "id": 24, "nombre": "Cate", "edad": 50, "gender": "F", "sueldo": 1851, "pais": "China" },
{ "id": 25, "nombre": "Kerstin", "edad": 57, "gender": "F", "sueldo": 1866, "pais": "United States" },
{ "id": 26, "nombre": "Benjamen", "edad": 54, "gender": "M", "sueldo": 1239, "pais": "Palestinian Territory" },
{ "id": 27, "nombre": "Leroi", "edad": 61, "gender": "M", "sueldo": 1911, "pais": "Sweden" },
{ "id": 28, "nombre": "Flossi", "edad": 65, "gender": "F", "sueldo": 1957, "pais": "Moldova" },
{ "id": 29, "nombre": "Claudio", "edad": 22, "gender": "M", "sueldo": 1119, "pais": "Indonesia" },
{ "id": 30, "nombre": "Eudora", "edad": 49, "gender": "F", "sueldo": 1465, "pais": "China" },
{ "id": 31, "nombre": "Gustavus", "edad": 24, "gender": "M", "sueldo": 1350, "pais": "China" },
{ "id": 32, "nombre": "Stewart", "edad": 59, "gender": "M", "sueldo": 1798, "pais": "Syria" },
{ "id": 33, "nombre": "Allyn", "edad": 24, "gender": "M", "sueldo": 1139, "pais": "China" },
{ "id": 34, "nombre": "Bianka", "edad": 44, "gender": "F", "sueldo": 1246, "pais": "Jordan" },
{ "id": 35, "nombre": "Ingunna", "edad": 24, "gender": "F", "sueldo": 1763, "pais": "Peru" },
{ "id": 36, "nombre": "Lissie", "edad": 65, "gender": "F", "sueldo": 1151, "pais": "Colombia" },
{ "id": 37, "nombre": "Emlen", "edad": 24, "gender": "M", "sueldo": 1201, "pais": "Botswana" },
{ "id": 38, "nombre": "Antonetta", "edad": 27, "gender": "F", "sueldo": 1882, "pais": "Republic of the Congo" },
{ "id": 39, "nombre": "Torin", "edad": 30, "gender": "M", "sueldo": 1463, "pais": "Thailand" },
{ "id": 40, "nombre": "Deloris", "edad": 18, "gender": "F", "sueldo": 1172, "pais": "China" },
{ "id": 41, "nombre": "Skippie", "edad": 37, "gender": "M", "sueldo": 1379, "pais": "Russia" },
{ "id": 42, "nombre": "Nikolai", "edad": 60, "gender": "M", "sueldo": 1677, "pais": "United States" },
{ "id": 43, "nombre": "Ranice", "edad": 58, "gender": "F", "sueldo": 1905, "pais": "Dominican Republic" },
{ "id": 44, "nombre": "Gladi", "edad": 55, "gender": "F", "sueldo": 1002, "pais": "Sweden" },
{ "id": 45, "nombre": "Lanny", "edad": 38, "gender": "F", "sueldo": 1484, "pais": "Philippines" },
{ "id": 46, "nombre": "Brigit", "edad": 54, "gender": "F", "sueldo": 1811, "pais": "Iraq" },
{ "id": 47, "nombre": "Gretta", "edad": 37, "gender": "F", "sueldo": 1757, "pais": "Peru" },
{ "id": 48, "nombre": "Ellsworth", "edad": 53, "gender": "M", "sueldo": 1730, "pais": "China" },
{ "id": 49, "nombre": "Madonna", "edad": 43, "gender": "F", "sueldo": 1136, "pais": "Indonesia" },
{ "id": 50, "nombre": "Forbes", "edad": 45, "gender": "M", "sueldo": 1678, "pais": "Poland" }]


