export const movies = [
    {"id":1,"titulo":"Legend of the Guardians: The Owls of Ga'Hoole"},
{"id":2,"titulo":"NeverEnding Story III, The"},
{"id":3,"titulo":"Thoughtcrimes"},
{"id":4,"titulo":"Man on the Train (Homme du train, L')"},
{"id":5,"titulo":"Daisy Kenyon"},
{"id":6,"titulo":"Exercice de l'État, L'"},
{"id":7,"titulo":"Wolf Children (Okami kodomo no ame to yuki)"},
{"id":8,"titulo":"Her"},
{"id":9,"titulo":"Last Real Men, The (Die letzten Männer)"},
{"id":10,"titulo":"Homework"},
{"id":11,"titulo":"Dry Summer (Susuz yaz) (Reflections)"},
{"id":12,"titulo":"Sodom and Gomorrah"},
{"id":13,"titulo":"NATO's Secret Armies (Gladio: L'esercito segreto della Nato)"},
{"id":14,"titulo":"Brand Upon the Brain!"},
{"id":15,"titulo":"Dream Home (Wai dor lei ah yut ho)"},
{"id":16,"titulo":"Comic Book Confidential"},
{"id":17,"titulo":"Lucky Texan, The"},
{"id":18,"titulo":"Manchurian Candidate, The"},
{"id":19,"titulo":"Cousins in Love (a.k.a. Tender Cousins) (Tendres Cousines)"},
{"id":20,"titulo":"Songs From the Second Floor (Sånger från andra våningen)"},
{"id":21,"titulo":"County Teacher, The (Venkovský ucitel)"},
{"id":22,"titulo":"Jack Ryan: Shadow Recruit"},
{"id":23,"titulo":"After Five in the Jungle (Nach Fünf im Urwald)"},
{"id":24,"titulo":"Down to Earth"},
{"id":25,"titulo":"Non-Stop"},
{"id":26,"titulo":"Southerner, The"},
{"id":27,"titulo":"Dear Wendy"},
{"id":28,"titulo":"Edward, My Son"},
{"id":29,"titulo":"How to Deal"},
{"id":30,"titulo":"Confessions from a Holiday Camp"},
{"id":31,"titulo":"Un Poliziotto Scomodo"},
{"id":32,"titulo":"Conquest, The (La conquête)"},
{"id":33,"titulo":"Copenhagen"},
{"id":34,"titulo":"Evil of Frankenstein, The"},
{"id":35,"titulo":"Indian Runner, The"},
{"id":36,"titulo":"Headfirst"},
{"id":37,"titulo":"Rush: Beyond the Lighted Stage"},
{"id":38,"titulo":"Red Road"},
{"id":39,"titulo":"Pal Joey"},
{"id":40,"titulo":"Teacher's Pet"},
{"id":41,"titulo":"Song of Bernadette, The"},
{"id":42,"titulo":"Ego"},
{"id":43,"titulo":"Kids, The (Mistons, Les) (Mischief Makers, The)"},
{"id":44,"titulo":"Newton Boys, The"},
{"id":45,"titulo":"Hairspray"},
{"id":46,"titulo":"Masti"},
{"id":47,"titulo":"Angel Named Billy, An"},
{"id":48,"titulo":"Dark Knight, The"},
{"id":49,"titulo":"Metropolis"},
{"id":50,"titulo":"Kitchen Stories (Salmer fra kjøkkenet)"}];